"""Closed-loop driver — Phase 2b's ``measure → propose → score → accept`` loop.

:func:`run_session` is the main entry. Per iteration:

1. STOP-file kill switch.
2. Schema lock check.
3. ``pytest`` gate.
4. Propose a candidate :class:`~jtx.composer.tuning.Tuning`.
5. Write the candidate to ``tuning.toml`` (allow-list enforced).
6. Cheap determinism re-check.
7. Score the full corpus.
8. Hard-floor check + ΔR comparison.
9. Accept (optionally commit) or reject (restore previous override).
10. Append a log line. Check termination caps.

The driver never pushes, never deletes branches, never amends —
accepted snapshots are simple new commits Jonno reviews via the
normal squash-merge workflow.
"""

from __future__ import annotations

import subprocess
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from jtx.composer.tuning import Tuning, reset_default_tuning_cache
from jtx.improve.corpus import Corpus
from jtx.improve.determinism import NonDeterministicReward, assert_deterministic
from jtx.improve.proposer import Proposal, RandomWalkProposer, write_tuning_toml
from jtx.improve.report import (
    IterationLog,
    SessionSummary,
    build_iteration_record,
    new_session_dir,
    write_summary,
)
from jtx.improve.reward import (
    RewardBreakdown,
    RewardWeights,
    compute_reward,
    hard_floor_violation,
)
from jtx.improve.safety import (
    AllowListViolation,
    assert_git_args_safe,
    assert_proposal_paths_clean,
    assert_schema_unchanged,
    run_pytest,
    stop_requested,
)
from jtx.model.setup import Setup
from jtx.persist.json_io import load_setup

_REPO_ROOT = Path(__file__).resolve().parents[2]
_TUNING_TOML = _REPO_ROOT / "tuning.toml"
_DEFAULT_OUT_ROOT = _REPO_ROOT / "eval_runs"


# ----------------------------------------------------------------------
# Session config + result.
# ----------------------------------------------------------------------


@dataclass(frozen=True)
class SessionConfig:
    """Knobs for one ``jtx-improve`` invocation.

    *budget_iter* + *budget_wall_s* + *plateau_rejections* are
    termination conditions; whichever triggers first ends the session.
    *commit* + *branch* control git side effects — ``commit=False``
    keeps the loop in dry-run mode for tests + smoke runs.
    """

    budget_iter: int = 50
    budget_wall_s: float = 4 * 60 * 60.0
    plateau_rejections: int = 25
    seed: int = 0
    params_per_step: int = 3
    temperature: float = 1.0
    cooling: float = 0.97
    hard_floor: float = 0.05
    pytest_args: tuple[str, ...] = ("-q", "--no-header")
    skip_pytest: bool = False
    commit: bool = True
    branch: str | None = None
    out_root: Path = _DEFAULT_OUT_ROOT


@dataclass
class SessionState:
    """Mutable per-session bookkeeping the driver carries between iterations."""

    config: SessionConfig
    corpus: Corpus
    setup: Setup
    weights: RewardWeights
    proposer: RandomWalkProposer
    initial_tuning: Tuning
    best_tuning: Tuning
    initial_breakdown: RewardBreakdown
    best_breakdown: RewardBreakdown
    session_dir: Path
    log: IterationLog
    started_at: datetime
    iterations: int = 0
    accepted: int = 0
    rejected: int = 0
    floor_blocks: int = 0
    consecutive_rejections: int = 0
    termination: str = "ran out of iterations"


# ----------------------------------------------------------------------
# Git helpers — every call goes through assert_git_args_safe.
# ----------------------------------------------------------------------


def _git(args: list[str], *, repo_root: Path = _REPO_ROOT) -> subprocess.CompletedProcess:
    assert_git_args_safe(args)
    return subprocess.run(
        ["git", *args], cwd=str(repo_root), check=True, capture_output=True, text=True
    )


def _maybe_create_branch(branch: str | None) -> str | None:
    """``git checkout -b <branch>`` from the current HEAD if requested."""
    if branch is None:
        return None
    _git(["checkout", "-b", branch])
    return branch


def _commit_tuning(iteration: int, R: float, R_delta: float) -> None:
    """Stage tuning.toml + commit. Hard fences via assert_git_args_safe."""
    _git(["add", str(_TUNING_TOML)])
    msg = (
        f"improve: iter {iteration} accepted (R={R:.4f}, ΔR={R_delta:+.4f})\n"
        f"\n"
        f"Auto-generated by jtx-improve Tier-A loop."
    )
    _git(["commit", "-m", msg])


# ----------------------------------------------------------------------
# Per-iteration step.
# ----------------------------------------------------------------------


def _apply_tuning(tuning: Tuning) -> None:
    """Write *tuning* to ``tuning.toml`` and invalidate the cached default.

    The compose() default-tuning cache reads ``tuning.toml`` lazily; if
    we mutate the file without invalidating, subsequent compose calls
    see the old snapshot and the optimizer measures a stale reward.
    """
    assert_proposal_paths_clean([_TUNING_TOML])
    write_tuning_toml(tuning, _TUNING_TOML)
    reset_default_tuning_cache()


def _step(state: SessionState) -> bool:
    """One iteration of the loop. Returns ``False`` if the loop must stop."""
    if stop_requested():
        state.termination = "STOP file present"
        return False

    if not state.config.skip_pytest:
        result = run_pytest(state.config.pytest_args)
        if not result.passed:
            state.termination = f"pytest red (rc={result.returncode})"
            return False

    try:
        assert_schema_unchanged()
    except RuntimeError as exc:
        state.termination = f"schema lock: {exc}"
        return False

    start = time.monotonic()
    proposal = state.proposer.propose(state.best_tuning)
    if not proposal.diff:
        # Proposer returned an effective no-op (every perturbation
        # rounded back to the existing value, e.g. small step for an
        # int field at a bound). Log and count so plateaus and the
        # iteration cap fire.
        state.iterations += 1
        state.rejected += 1
        state.consecutive_rejections += 1
        state.log.append(
            build_iteration_record(
                iteration=state.iterations,
                accepted=False,
                reason="no-op proposal (all perturbations clipped)",
                before=state.best_breakdown,
                after=state.best_breakdown,
                proposal=proposal,
                elapsed_s=time.monotonic() - start,
            )
        )
        return _continue(state)

    try:
        _apply_tuning(proposal.tuning)
    except AllowListViolation as exc:
        state.iterations += 1
        state.rejected += 1
        state.consecutive_rejections += 1
        state.log.append(
            build_iteration_record(
                iteration=state.iterations,
                accepted=False,
                reason=f"allow-list violation: {exc}",
                before=state.best_breakdown,
                after=state.best_breakdown,
                proposal=proposal,
                elapsed_s=time.monotonic() - start,
            )
        )
        return _continue(state)

    # Cheap determinism re-check on a sub-corpus. If this fails, the
    # reward signal is unreliable — abort the session.
    try:
        assert_deterministic(
            state.corpus,
            proposal.tuning,
            setup=state.setup,
            weights=state.weights,
            quick=True,
        )
    except NonDeterministicReward as exc:
        state.termination = f"non-deterministic reward: {exc}"
        # Restore the previous best tuning before exiting so the
        # working tree carries the last-known-good snapshot.
        _apply_tuning(state.best_tuning)
        return False

    candidate = compute_reward(
        state.corpus, proposal.tuning, weights=state.weights, setup=state.setup
    )

    floor_msg = hard_floor_violation(
        candidate, state.best_breakdown, epsilon=state.config.hard_floor
    )
    if floor_msg is not None:
        state.iterations += 1
        state.rejected += 1
        state.floor_blocks += 1
        state.consecutive_rejections += 1
        _record_and_revert(
            state, proposal, candidate,
            accepted=False, reason=floor_msg, elapsed=start,
        )
        return _continue(state)

    improved = candidate.R > state.best_breakdown.R
    if improved:
        state.iterations += 1
        state.accepted += 1
        state.consecutive_rejections = 0
        previous_best = state.best_breakdown
        delta = candidate.R - previous_best.R
        state.best_breakdown = candidate
        state.best_tuning = proposal.tuning
        state.log.append(
            build_iteration_record(
                iteration=state.iterations,
                accepted=True,
                reason=f"ΔR={delta:+.6f}",
                before=previous_best,
                after=candidate,
                proposal=proposal,
                elapsed_s=time.monotonic() - start,
            )
        )
        if state.config.commit:
            _commit_tuning(state.iterations, candidate.R, delta)
        return _continue(state)

    # Reject.
    state.iterations += 1
    state.rejected += 1
    state.consecutive_rejections += 1
    _record_and_revert(
        state, proposal, candidate, accepted=False,
        reason=f"ΔR={candidate.R - state.best_breakdown.R:+.6f} (no improvement)",
        elapsed=start,
    )
    return _continue(state)


def _record_and_revert(
    state: SessionState,
    proposal: Proposal,
    candidate: RewardBreakdown,
    *,
    accepted: bool,
    reason: str,
    elapsed: float,
) -> None:
    """Append a rejection log line and roll tuning.toml back to the running best."""
    state.log.append(
        build_iteration_record(
            iteration=state.iterations,
            accepted=accepted,
            reason=reason,
            before=state.best_breakdown,
            after=candidate,
            proposal=proposal,
            elapsed_s=time.monotonic() - elapsed,
        )
    )
    _apply_tuning(state.best_tuning)


def _continue(state: SessionState) -> bool:
    """Apply the termination policy after each iteration."""
    cfg = state.config
    if state.iterations >= cfg.budget_iter:
        state.termination = f"iteration cap ({cfg.budget_iter})"
        return False
    elapsed = (datetime.now(UTC) - state.started_at).total_seconds()
    if elapsed >= cfg.budget_wall_s:
        state.termination = f"wall clock budget ({cfg.budget_wall_s:.0f}s)"
        return False
    if state.consecutive_rejections >= cfg.plateau_rejections:
        state.termination = f"plateau ({cfg.plateau_rejections} consecutive rejections)"
        return False
    return True


# ----------------------------------------------------------------------
# Public entry.
# ----------------------------------------------------------------------


def run_session(
    *,
    corpus: Corpus,
    config: SessionConfig | None = None,
    weights: RewardWeights | None = None,
    initial_tuning: Tuning | None = None,
) -> SessionSummary:
    """Run one Tier-A session against *corpus*; return a SessionSummary."""
    cfg = config or SessionConfig()
    w = weights or RewardWeights()
    setup = load_setup(corpus.setup_path)

    initial = initial_tuning if initial_tuning is not None else Tuning()
    _apply_tuning(initial)

    # Full-corpus determinism check at session start.
    initial_breakdown = assert_deterministic(
        corpus, initial, setup=setup, weights=w, quick=False
    )

    proposer = RandomWalkProposer(
        specs=_default_specs(),
        seed=cfg.seed,
        params_per_step=cfg.params_per_step,
        temperature=cfg.temperature,
        cooling=cfg.cooling,
    )

    if cfg.commit:
        _maybe_create_branch(cfg.branch)
    session_dir = new_session_dir(cfg.out_root)
    log = IterationLog(session_dir / "log.jsonl")
    started_at = datetime.now(UTC)

    state = SessionState(
        config=cfg,
        corpus=corpus,
        setup=setup,
        weights=w,
        proposer=proposer,
        initial_tuning=initial,
        best_tuning=initial,
        initial_breakdown=initial_breakdown,
        best_breakdown=initial_breakdown,
        session_dir=session_dir,
        log=log,
        started_at=started_at,
    )

    try:
        while _step(state):
            pass
    finally:
        log.close()

    write_summary(
        session_dir,
        started_at=started_at,
        ended_at=datetime.now(UTC),
        initial=state.initial_breakdown,
        best=state.best_breakdown,
        accepted_iters=state.accepted,
        rejected_iters=state.rejected,
        floor_blocks=state.floor_blocks,
        termination=state.termination,
    )

    return SessionSummary(
        session_dir=session_dir,
        iterations=state.iterations,
        accepted=state.accepted,
        rejected=state.rejected,
        best_R=state.best_breakdown.R,
        initial_R=state.initial_breakdown.R,
    )


def _default_specs():
    """Imported lazily so the driver module stays cheap to import."""
    from jtx.improve.proposer import default_param_specs

    return default_param_specs()


__all__ = [
    "SessionConfig",
    "SessionState",
    "run_session",
]
