"""Per-bar context passed into every algorithm's ``generate_bar`` call.

Algorithms read this; they don't reach back into the Song model. That
keeps the algorithm boundary thin enough to also be the future
external-input boundary (a ``RootProvider`` can override
``chord_root_semitones`` per bar without algorithm changes).

Algorithms **must** use ``ctx.rng`` for any randomness. Calling the bare
``random`` module breaks the reproducibility contract pinned by
:mod:`jtx.seed`.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

from jtx.engine.events import Event
from jtx.model.song import Key, KnobDict
from jtx.seed import derive_hold_seed, derive_loop_seed


@dataclass
class BarContext:
    """Read-mostly context for one (bar × voice) generate call.

    Not frozen — :class:`random.Random` isn't trivially immutable — but
    treat the data fields as read-only inside algorithms. The scheduler
    constructs a fresh ``BarContext`` per (bar, voice); mutating it has
    no effect on subsequent bars.
    """

    bar_index: int
    """0-based bar index within the current part."""

    tick_offset: int
    """Absolute tick at which this bar starts (since playback began)."""

    ticks_per_bar: int
    """Ticks in one bar at the active PPQ + meter. Algorithms emit
    events with ``0 <= tick < ticks_per_bar`` *relative to bar start*;
    the scheduler adds :attr:`tick_offset` before dispatching."""

    tempo_bpm: float
    ppq: int

    key: Key
    """Active key for this bar — usually the song key, possibly
    overridden by a per-part voice key for modal-mixture moments."""

    chord_root_semitones: int = 0
    """Semitones above the song's tonic for the current chord. The
    :class:`jtx.engine.root_provider.RootProvider` (later milestone)
    sources this — default 0 (= song tonic) until that lands."""

    pattern_knobs: KnobDict = field(default_factory=dict)
    """Resolved pattern knobs at this bar's scope (part > song > role
    default > algorithm default). Resolution lives in the part/voice
    glue layer, not here."""

    mix_knobs: KnobDict = field(default_factory=dict)
    """Resolved per-voice mix-pass knobs (sidechain / fade /
    evolution). Renamed from ``feel_knobs`` in schema v3; per-voice
    bar-internal feel keys are gone — see :attr:`song_feel`."""

    song_feel: dict[str, float] = field(default_factory=dict)
    """Read-only snapshot of the song's global feel knobs at this bar
    (pump, groove, drive, tension, wander). Algorithms that legitimately
    consult feel (drum_kit reading drive for ghost prob, wander for
    polyrhythm chance) read it here. The post-emit feel pass also reads
    this — it no longer takes per-voice feel input."""

    part_progress: float = 0.0
    """0..1 normalised position within the active part. Bar 0 = 0.0;
    last bar of an N-bar part = 1.0 (linear). One-bar parts are
    treated as progress=1.0 from the outset.

    Algorithms that want to evolve within a part (drum_kit's snare
    density ramp, build-up fills, …) read this."""

    part_intensity: float = 0.5
    """Linear interpolation of the part's ``intensity_start`` →
    ``intensity_end`` at the current bar, scaled by the song-level
    ``Tension`` knob. Drum_kit's headline knob for choosing how
    busy a piece's pattern is."""

    rng: random.Random = field(default_factory=random.Random)
    """Pre-seeded RNG for this (song, part, voice, bar) tuple — see
    :func:`jtx.seed.derive_bar_seed`."""

    part_voice_seed: int = 0
    """Per-(part, voice) seed used by the cyclic-RNG factories
    :meth:`rng_loop` / :meth:`rng_hold`. Defaulted so existing test
    constructors that build a ``BarContext`` directly keep working — the
    SongPlayer always populates it for real playback."""

    source_events: list[Event] | None = None
    """Only set for ``follower`` voices: the source voice's events for
    this bar, already generated by the engine glue layer. ``None`` for
    every non-follower algorithm."""

    prev_source_events: list[Event] | None = None
    """Only set for ``follower`` voices: the source voice's events from
    the *previous* bar. ``None`` on the first bar of a part (no history
    yet) or for non-follower algorithms. Reserved for the upcoming
    follower-lookback work; algorithms that don't need it can ignore."""

    def rng_loop(self, period: int | str, salt: str = "") -> random.Random:
        """Return an RNG that loops on an N-bar period (``bar_index % N``).

        Bars at the same slot inside the period share the same seed, so
        consecutive periods replay the same draw sequence — a 4-bar
        phrase that repeats forever. ``period=0`` is the off-sentinel and
        returns :attr:`rng` (bar-fresh). ``period="part"`` yields a
        constant RNG across the whole part. ``period=1`` makes every bar
        identical (all bars share ``slot=0``).
        """
        if period == 0:
            return self.rng
        return random.Random(derive_loop_seed(self.part_voice_seed, period, self.bar_index, salt))

    def rng_hold(self, period: int | str, salt: str = "") -> random.Random:
        """Return an RNG that is held for N bars then changes (``bar_index // N``).

        Bars within the same epoch share the same seed; the seed jumps
        every ``period`` bars. ``period=0`` is the off-sentinel and
        returns :attr:`rng`. ``period="part"`` yields a constant RNG
        across the whole part. Used by ``motif_phrase`` to keep base
        motif content stable across a phrase.
        """
        if period == 0:
            return self.rng
        return random.Random(derive_hold_seed(self.part_voice_seed, period, self.bar_index, salt))
